console_error_message: '&8[&c*&8] &cYou are unable to execute this command!'
no_perm_error: '&8[&c*&8] &cYou are unable to execute this command!'

#Fly Command
FlyCmd:
   fly_active: '&8[&a*&8] &7You have &aenabled &7fly!'
   fly_deactived: '&8[&a*&8] &7You have &cdisabled &7fly!'
   
#Join System

firstjoin_message: '&a<player> &7has joined the server for the first time!'
join_message: '&e<player> &7has joined the server!'

#Website
WebsiteCmd:
   website: '&4Link to website: &5https://11c.org/'
   
#Leave System
LeaveListener:
   leave_event: '&a<player> &7has left the server.'
   
#Gamemode System
GmSys:
   c: '&8[&a*&8] &7You have &aentered &7Creative mode!'
   s: '&8[&a*&8] &7You have &aentered &7Survival mode!'
   sp: '&8[&a*&8] &7You have &aentered &7Spectator mode!'
   ad: '&8[&a*&8] &7You have &aentered &7Adventure mode!'

#About Command   
AboutCmd:
   about: "&5Plugin Name: &6c11C Plugin\n &5Plugin Version: &60.9.0\n Hope you have a fun time!"
   
#Help Command
HelpCmd:
   help: "&6About: &4Information of 11C's Plugin \n  &6Fly: &4Allow Flight \n &6CHelp: &4Information of 11C's Commands \n &6Website: &4Link to 11C's Official Website\n &6Discord: &4Link to 11C's Official Discord \n &6Credits: &4Who worked on 11C Plugin \n &6Youtube: &411C's Official Youtube \n &6Hub: &4Teleports you to the server Hub \n &6GMS: &4Switches your gamemode to survival \n &6GMSP: &4Switches your gamemode to spectator \n &6GMC: &4Switches your gamemode to creative \n &6GMAD: &4Switches your gamemode to adventure"
